### ISSUE TITLE
Crash when enter VRChat from Oculus Quest 2, Virtual Desktop environment

### ISSUE THREAD

**Issue by alexiscatnip** [ju1ce/Mediapipe-VR-Fullbody-Tracking#14]
Able to auto calibrate
Able to see the skeleton in SteamVR environment.
Stop executing when I click VRChat. 

Python 3.9.2
Release 0.6

Log:
Postcalib y value:  -83.56233936752928
Changed scale value to 1.0836985136298132
**Traceback (most recent call last):
  File "mediapipepose.py", line 243, in <module>
IndexError: list index out of range
[26228] Failed to execute script 'mediapipepose' due to unhandled exception!**

**Comment by FerLuisxd** [comment]
Probably ram or vram? What are your pc specs

**Comment by alexiscatnip** [comment]
i think my steamVR crashed at a specific time to cause this error
