### ISSUE TITLE
Runs at 70fps, but is very laggy in VR.

### ISSUE THREAD

**Issue by GreenBeanGravy** [ju1ce/Mediapipe-VR-Fullbody-Tracking#23]
Mediapipe Pose runs SUPER smooth with my setup with little to no jitter and perfect accuracy. However, this is not the case when in VR. My movements are delayed by 100-150ms (ok I can deal with that no problem) but the trackers seem to be moving around somewhere between 20-30fps and jitter a LOT. I have played with the smoothness settings and while they do help, I can't seem to find an inbetween for smooth tracking and high accuracy. What confuses me the most is that Mediapipe Pose hardly even seems to be jittering at all in the first place!

**Comment by ju1ce** [comment]
There are a few different steps that happen when translating the 2d pose to 3d which introduces extra jitter, such as:
- Estimating depth from camera is extremely innacurate, and is completely guessed
- Mediapipe does not know how the camera is oriented and that it is static, so it keeps guessing which way is the floor and how much you are leaning
- The headset position in steamvr is being alligned to the head position in mediapipe

So, getting perfect tracking is hard, but there are ways to improve it:
- Better lighting and lighter clothes, so you are seen well in the camera, help a lot. If your whole outfit is just black, it will have a lot of trouble. It also helps if your pants are diffrent color than shirt, so it has a clear seperation.
- Having camera head high and pointing downward sometimes also helps

As for the smoothing parameters, the apriltagtrackers wiki has some graphs to help understand what exactly they do: https://github.com/ju1ce/April-Tag-VR-FullBody-Tracker/wiki/Refining-parameters

The smoothing window doesnt work as well for mediapipe as for att, so its good to have it low. If you download the latest version of apriltagtrackers and install that driver, you will also have an option to disable it and use additional smoothing only.
