### ISSUE TITLE
Not connecting to SteamVR after 10 tries

### ISSUE THREAD

**Issue by Gboy12345** [ju1ce/Mediapipe-VR-Fullbody-Tracking#32]
![Screenshot 2023-04-04 144358](https://user-images.githubusercontent.com/108963387/229929544-b083ce12-cd88-4f6d-92d8-1a08e58981c0.png)

**Comment by ju1ce** [comment]
Did you install the driver properly? Check that running install_driver.bat returns no error.
Also, check steamvr settings -> startup -> addons, make sure that apriltagtrackers is listed and enabled. Sometimes steamvr disables things for no reason...
