### ISSUE TITLE
Camera view showing just an orange screen

### ISSUE THREAD

**Issue by 6543ozne** [ju1ce/Mediapipe-VR-Fullbody-Tracking#35]
Everything goes well but when I press save and continue, the out window shows an orange screen
![image](https://github.com/ju1ce/Mediapipe-VR-Fullbody-Tracking/assets/105403431/19acfeb0-b36f-4a76-b43f-02eca670d7e4)

And when I set it to camera 2, it's a sky blue screen
![image](https://github.com/ju1ce/Mediapipe-VR-Fullbody-Tracking/assets/105403431/6ddb4f2f-f4d4-41c4-a9e0-551701ff32d0)

if its because of the os, im using windows 11

**Comment by ju1ce** [comment]
Im guessing you are the person that got this fixed on the discord and the solution was to set camera ID to 0, but in any case:

Orange and blue screens are pretty weird, so i would guess its an issue with some virtual camera app that is taking the selected ID. Just check others (0,1,2 etc)
