### ISSUE TITLE
Trackers Not Working

### ISSUE THREAD

**Issue by DrCoomerPhD** [ju1ce/Mediapipe-VR-Fullbody-Tracking#37]
so i installed the drivers, i ran the start_mediapipepose.bat i configured the settings, i pressed Save And Continue, 2 windows appear and after 2 seconds they dissapear. SteamVR Appears To Have (I Think) 6 Tracker Icon's, which all say "Move To Enable Tracker" (smthing like that). When I Go Try A Game That Supports Tracker's, They Don't Work. Ill Now Show Some Settings
![image](https://github.com/ju1ce/Mediapipe-VR-Fullbody-Tracking/assets/110489194/86744604-4d57-473a-ac51-d006c57bf0a0)

**Comment by ju1ce** [comment]
That sounds like the camera ID being wrong. Have you tries other IDs besides 1? It will probably be 0, but could also be 2,3 etc.

Also, you probably dont need advanced mode, and you dont need to enable the webui if you are using steamvr.

**Comment by DrCoomerPhD** [comment]
> That sounds like the camera ID being wrong. Have you tries other IDs besides 1? It will probably be 0, but could also be 2,3 etc.
> 
> Also, you probably dont need advanced mode, and you dont need to enable the webui if you are using steamvr.

i figured it out, so what i did, i uninstalled the drivers, i deleted the whole mediapipe folder, re extracted the mediapipe folder, i installed back the drivers i ran it, i putted 1, didn't work, i put 2 didn't work and so on, until, i put 0, it worked, thanks tho, i fixed by myself.
